apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hermes.fullname" . }}-api
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      {{- include "hermes.selectorLabels" . | nindent 6 }}
