apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hermes.fullname" . }}-home
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.hermesHome.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.hermesHome.size }}
