apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes.fullname" . }}-api
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/component: api
    {{- include "hermes.selectorLabels" . | nindent 4 }}
