{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "hermes.fullname" . }}-secrets
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: hermes-secrets
    creationPolicy: Owner
  data:
  {{- range $key, $remoteRef := .Values.externalSecrets.remoteRefs }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $remoteRef }}
  {{- end }}
{{- end }}
